services:
  dclm-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:8000"

  dclm-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:80"

networks:
  default:
    name: entrepreneur-dclm-a1spks_default
    labels:
      com.docker.compose.network: "default"