version: '3.8'

services:
  dclm-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dclm-backend
    restart: always
    ports:
      - "9000:8000"
    environment:
      - PORT=8000
      - CORS_ORIGINS=http://127.0.0.1:3001,http://localhost:3001
      # Your Google env vars here
    networks:
      - dclm-network

  dclm-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dclm-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - dclm-backend
    networks:
      - dclm-network

networks:
  dclm-network:
    driver: bridge